#!/usr/bin/env bash
set -eum

env bwrap \
  --ro-bind /nix/store{,} \
  --ro-bind /etc{,} \
  --ro-bind /run/current-system{,} \
  --ro-bind "$HOME"/.cache/tealdeer{,} \
  --ro-bind "$HOME"/.config/helix{,} \
  --ro-bind "$HOME"/.ssh/known_hosts{,} \
  --ro-bind "$HOME"/.ssh/config{,} \
  --ro-bind "$HOME"/.bashrc{,} \
  --ro-bind "$HOME"/.config/starship.toml{,} \
  --ro-bind "$HOME"/.config/git{,} \
  --bind "$XDG_RUNTIME_DIR"/wayland-0{,} \
  --bind "$XDG_RUNTIME_DIR"/pulse{,} \
  --bind /run/user/1000/ssh-agent{,} \
  --bind "$HOME"/.cache/blesh{,} \
  --bind "$HOME"/Code{,} \
  --bind /bin/sh{,} \
  --bind /usr/bin/env{,} \
  --dir "$HOME" \
  --dir /tmp \
  --dev /dev \
  --proc /proc \
  --unshare-user \
  --unshare-pid \
  --unshare-uts \
  --unshare-cgroup \
  --share-net \
  --die-with-parent \
  --cap-drop ALL \
  --hostname code-sandbox \
  $SHELL
