#!/usr/bin/env bash

APP_NAME="org.gnome.Rhythmbox3"
APP_FOLDER="$XDG_RUNTIME_DIR/app/$APP_NAME"
mkdir -p "$APP_FOLDER"

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
  export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
fi

# A sandboxed dbus filter that 
# makes things a little safer
#
# Bwrap was initially for --die-with-parent,
# but was expanded to fix bugs related to portals
set_up_dbus_proxy() {
  echo "Starting xdg-dbus-proxy..."
  bwrap \
    --new-session \
    --ro-bind /nix/store{,} \
    --ro-bind /etc{,} \
    --ro-bind /run/current-system{,} \
    --bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
    --ro-bind-data 3 "/.flatpak-info" \
    --die-with-parent \
    -- \
    xdg-dbus-proxy \
    "$DBUS_SESSION_BUS_ADDRESS" \
    "$APP_FOLDER/bus" \
    --filter \
    --log \
    --own="org.gnome.Rhythmbox3" \
    --own="org.mpris.MediaPlayer2.rhythmbox" \
    --talk="org.mpris.MediaPlayer2.Player" \
    --talk="org.gnome.SettingsDaemon.MediaKeys" \
    --talk="ca.desrt.dconf" \
    --talk="org.gtk.vfs.*" 3<<EOF
[Application]
name=$APP_NAME
EOF
}

set -eum
set_up_dbus_proxy &
sleep 0.1
bwrap \
--new-session \
--ro-bind /nix/store{,} \
--ro-bind /etc{,} \
--ro-bind /run/current-system{,} \
--ro-bind /run/dbus /run/dbus \
--bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
--bind "$XDG_RUNTIME_DIR/doc" "$XDG_RUNTIME_DIR/doc" \
--bind "$APP_FOLDER/bus" "$XDG_RUNTIME_DIR/bus" \
--bind "$XDG_RUNTIME_DIR"/wayland-0{,} \
--bind "$XDG_RUNTIME_DIR"/pipewire-0{,} \
--bind "$HOME"/Music{,} \
--bind "$HOME"/.local/share/rhythmbox{,} \
--bind "$HOME"/.cache/rhythmbox{,} \
--bind "$HOME"/.config/glib-2.0{,} \
--dev-bind /dev/dri /dev/dri \
--dir /tmp \
--dev /dev \
--proc /proc \
--unshare-user \
--unshare-pid \
--unshare-uts \
--unshare-cgroup \
--unshare-net \
--unshare-ipc \
--unshare-all \
--die-with-parent \
--cap-drop ALL \
--hostname gui-sandbox \
--ro-bind-data 3 "/.flatpak-info" \
-- \
rhythmbox "$@" \
3<<EOF
[Application]
name=$APP_NAME
EOF
