#!/usr/bin/env bash
random_scope="tor-browser-"$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
systemd-run --unit=$random_scope --user --scope -p MemoryHigh=400M -p MemoryMax=400M tor-browser-sandbox-unrestricted
